- .gitignore
- tests/tests/conftest.py
This allows tests to be run in any directory (not just the root directory of the project).
> Use relative paths for test data directories

- .github/workflows/test_and_deploy.yml
- .pre-commit-config.yaml
- tox.ini
Also fixes https://github.com/brainglobe/cellfinder/issues/194 by using the tox file
> Use re-usable GH actions to run CI

- setup.py
Reverts brainglobe/cellfinder#205 As discussed with Adam on Slack.
> Revert "Don't specify QT backend in requirements"

- .pre-commit-config.yaml
- cellfinder/analyse/analyse.py
- cellfinder/extract/extract_cubes.py
- cellfinder/figures/heatmap.py
- cellfinder/main.py
- cellfinder/tools/parser.py
- pyproject.toml
- setup.cfg
- tests/tests/test_integration/test_extract.py
This applies the standard pre-commit-config.yaml file from https://github.com/SainsburyWellcomeCentre/python-cookiecutter, and fixes files as needed for this new config.
> Use standard pre-commit config

- setup.py
Force version of brainglobe-utils that has the `DefaultDict` fix.
This will let us trigger a new release that means the `cellfinder-core` tests should pass.
> Force version of brainglobe-utils that has the `DefaultDict` fix.

- cellfinder/__init__.py
- setup.py
Apologies for the PR noise.
New version in setup.py for patched version, so we can release `v0.7.0` to PyPI.
There look to be old tags (v0.6.0) that are datestamped 2020, but the latest releases are from 2021 and only reach v0.4.21.
Bumping to version `v0.7.0` to skip around this ambiguity. Will generate release notes once pushed to PyPI.
> Update manual version

- .github/workflows/test_and_deploy.yml
- cellfinder/main.py
- cellfinder/tools/parser.py
- cellfinder/tools/prep.py
- pyproject.toml
- tox.ini
Updates cellfinder to be compliant with the upcoming release of `brainreg` version 1, as per https://github.com/brainglobe/brainreg/pull/146.
Note that `pyproject.toml` now pins the `brainreg` version to be `v1.0.0` to prevent users from installing an old version of `brainreg` through their `cellfinder` install.
This needs to be merged after https://github.com/brainglobe/brainreg/pull/146 _and_ the new release of `brainreg` (version 1.0.0) is available on PyPI.
CI will fail until these conditions are met.
`cellfinder` will need a new release. This release version _must_ be <`v1.0.0`.
> Update to brainreg v1 compliance

- tests/tests/test_unit/test_analyse.py
- tox.ini
@alessandrofelder Noticed your test data wasn't being found because our `MANIFEST` is told to ignore the `tests` directory when packaging.
Changed the `tox` command and paths in the to-be regression tests to point to the repository clone, which should then resolve the paths correctly using the repo clone.
> Fix pathing problems

- cellfinder/analyse/analyse.py
- tests/data/analyse/region_totals.csv
- tests/data/analyse/region_totals_regression_pandas1_5_3.csv
- tests/data/analyse/volumes.csv
- tests/tests/test_unit/test_analyse.py
- tests/tests/test_unit/test_tools/test_system.py
- tox.ini
Newer versions of `pandas` break the analysis code, due to the deprecation and removal of `pandas.Dataframe.append`.
* Replaces the use of `pandas.Dataframe.append` with `brainglobe_utils.pandas.safe_concat` in `analyse.get_region_totals()`
* Adds a regression test to check that the result is still the same as with `pandas` 1.5.3, ie before deprecation).
Closes #254 
* Regression data generated with `pandas 1.5.3` and test written.
Nope
Nope
> Replace `pandas.df.append` with `safe_concat`

- README.md
- cellfinder/__init__.py
- pyproject.toml
- tox.ini
See https://github.com/brainglobe/BrainGlobe/issues/45
Prepares the CLI-cellfinder package for migration into brainglobe-workflows.
Note that we do not want to archive the repository, since we need it for when we merge in cellfinder-core and cellfinder-napari.
On merge, tag new release version so that the deprecation warning files through to PyPI.
> Prepare for migration

- .github/workflows/test_and_deploy.yml
- README.md
- pyproject.toml
- Drop python 3.8 official support
- Point README to brainmapper information, rather than old cellfinder-CLI
For the release of v1.0.0 we had to suppress the check on the `brainmapper` command-line interface, since we had a circular dependency:
Workflows needs cellfinder v1.0.0 on PyPI to download it and test-run brainmapper -> cellfinder v1.0.0 can't check that brainmapper works since it needs the name available in workflows.
This PR reinstates the command-line tool check in our CI workflow.
This is something of a code duplication (ideally the CI in this repo would call some CI in workflows) but it safeguards us for now, and we can always set this up ourselves after the migration is complete.
> Reinstate brainmapper ci check

- .github/workflows/test_and_deploy.yml
- benchmarks/benchmarks/tools/prep.py
- cellfinder/core/main.py
- cellfinder/core/tools/prep.py
- cellfinder/core/train/train_yml.py
Combines two very similar functions and also removes a seemingly redundant function arguement. 
@sfmig I've somewhat naively updated the benchmarking code, but I may have done this wrong.
Closes #272
> Prep merge

- cellfinder/core/detect/detect.py
> Raise more informative error message when data with a large z-spacing is used

- cellfinder/napari/train/train.py
- pyproject.toml
This copies the code used for the detection widget to add a scroll bar to the training widget (allowing it to be used on small screens).
The curation widget doesn't use magicgui, so the solution can't be copy & pasted. Considering the widget is much smaller though, I don't think it needs a scroll bar.
Also adds a missing dependency
Closes https://github.com/brainglobe/cellfinder/issues/341
> Adds vertical scroll bar to the training widget

- cellfinder/core/detect/detect.py
- cellfinder/core/detect/filters/volume/volume_filter.py
Slightly more verbose debug logs for some parts of detection.
Might help us with memory issues in #372 
#372
Visual inspection of running a simple script on the SWC cluster.
Three extra lines of debug logs never hurt anyone :) 
Nope.
Nope
- [n/a] Tests have been added to cover all new functionality (unit & integration)
- [n/a] The documentation has been updated to reflect any changes
> improve detection debug logs

- .github/workflows/test_include_guard.yaml
- cellfinder/__init__.py
- pyproject.toml
This PR:
- Updates the dependencies and dev dependencies to work with Keras 3.0
- Replaces the Tensorflow check with a Keras check (tested in CI).
**Notes:**
- To avoid TF [overwriting](https://keras.io/getting_started/#installing-keras-3) the Keras version to 2.x, I pinned the TF version to a specific 2.16-nightly for now (same as they do in the [keras repo](https://github.com/keras-team/keras/blob/master/requirements.txt)).
- Before migrating to Keras 3.0, we checked that cellfinder tools throw an error if Tensorflow is not present. This PR replaces this check with an equivalent check for Keras.
- The CI checks that are failing (running package tests, brainmapper tests and running tests without numba) are dealt with in a [follow-up PR](https://github.com/brainglobe/cellfinder/pull/373). …
> Test Keras is present

- .github/workflows/test_and_deploy.yml
- .github/workflows/test_include_guard.yaml
- cellfinder/__init__.py
Changed some missed referenced to tensorflow -> Keras.
Changes are in github worklows (job names), some comments and in warning/error messages.
> Replace TF references in comments and warning messages

- .github/workflows/test_and_deploy.yml
- .github/workflows/test_include_guard.yaml
- cellfinder/__init__.py
- cellfinder/core/classify/resnet.py
- cellfinder/core/tools/prep.py
- cellfinder/core/tools/tf.py
- pyproject.toml
With this PR, cellfinder tests pass with Keras 3.0 and both the tensorflow and the JAX backend 🥳 
Specifically:
- I added checks similar to previously existing ones, that checked if `tensorflow` was installed in the environment before importing `cellfinder`. Now we check if `keras` is installed, and if it has an appropriate backend installed. I modified the CI check accordingly.
- I configured tox to run tests using the tensorflow backend and the JAX backend.
- for the brainmapper tests we run in CI, I added a `pip install` step that installs the (for now pinned) tensorflow version compatible with Keras 3.0.0. I am (temporarily) setting tensorflow as the default backend for Keras if none is defined.
- for the time being I pinned Keras and TF to specific versions, but happy to inspect that …
> Cellfinder with Keras 3.0 and jax backend

- .github/workflows/test_and_deploy.yml
- cellfinder/core/train/train_yml.py
- pyproject.toml
- Use JAX backend for windows tests
> Run cellfinder with JAX in Windows tests in CI

- cellfinder/core/train/train_yml.py
Trying to continue training without passing a trained model/model weights was leading to a crash.
Fixes the order arguments are passed to `prep_model_weights` in `cellfinder/core/train/train_yml.py` to match with the rest of the codebase.
Please reference any existing issues/PRs that relate to this PR.
All previous tests pass locally on Ubuntu.
No.
No
> Switch order of arguments passed to prep_model_weights in train_yml.py

- pyproject.toml
`brainglobe-utils` and `brainglobe-napari-io` currently don't have minimum pinned versions.
This PR pins the minimum `brainglobe-utils` version to 0.4.2, and `brainglobe-napari-io` to 0.3.4
All tests pass locally.
No.
No.
> Pin minimum brainglobe dependency versions

- cellfinder/core/download/cli.py
- cellfinder/core/download/download.py
- cellfinder/core/tools/prep.py
- cellfinder/core/tools/source_files.py
Specifying a non-default model currently writes to package files (which is a bad idea in general, but in particular causes errors on shared systems like our local HPC).
User-specified model configuration files are written to user folder instead.
It also documents and renames some of the functions involved.
Closes #393
Existing tests pass.
No.
No.
> basic fix avoiding writing to package files

- cellfinder/napari/detect/detect.py
The problem is that when large images are open in napari, every time I try to edit a parameter (and I imagine - when the progress bar is updated), the gui freezes for a bit. After some testing I realized that every time *any* parameter updates, magicgui is processing something for all the parameters in the root widget. But, this processing takes particularly long for image parameters, especially for large images (maybe magicgui gets some image data?).
You can see this effect in the video where I change the num threads without and with images being open.
main branch with no images open:
https://github.com/brainglobe/cellfinder/assets/1644286/f93a3063-9f19-4f91-b5f7-b2979dcf2ad3
main branch with an image open. You can see the lag: …
> Separate napari image parameter to prevent magicgui slowdown

- .github/workflows/test_and_deploy.yml
- pyproject.toml
Codecov is currently complaining on all actions runs with: `secret-codecov-token is not set. This will be required in the future. See https://docs.codecov.com/docs/quick-start#step-2-get-the-repository-upload-token on how to get a token.` and `Codecov: Failed to properly upload report: The process 'D:\a\_actions\codecov\codecov-action\v4\dist\codecov.exe' failed with exit code 1`
This PR ensures `test_and_deploy` is using the codecov token, as recommended in the [readme for the neuroinformatics unit test action](https://github.com/neuroinformatics-unit/actions/tree/main/test#python-test-action)
None
Hopefully codecov won't error on the github actions runs for this PR
No
No
> Add codecov token

- .github/workflows/test_and_deploy.yml
- .github/workflows/test_include_guard.yaml
`macos-latest` is now a Silicon Mac runner, so we need to adapt CI accordingly
* ensures CI is run on both Mac chip architectures
* runs tensorflow include guard tests on Silicon mac instead.
Partial solution to https://github.com/brainglobe/BrainGlobe/issues/63
CI that was breaking before, now passes
Now
No
- [n/a] The code has been tested locally
- [n/a] Tests have been added to cover all new functionality (unit & integration)
- [n/a] The documentation has been updated to reflect any changes
> Adapt CI so it covers both new and old Macs, and installs required additional dependencies on M1

- cellfinder/core/detect/detect.py
- cellfinder/core/detect/filters/volume/ball_filter.py
- cellfinder/core/detect/filters/volume/structure_detection.py
- cellfinder/core/detect/filters/volume/structure_splitting.py
- cellfinder/core/detect/filters/volume/volume_filter.py
- tests/core/test_unit/test_detect/test_filters/test_volume_filters/test_structure_detection.py
All credit to #398 and @matham, just needed these changes to take a little detour via this branch so I could test them more in-depth.
Merges in the changes from #398 after some more testing.
-
For some practical triple-checking, I ran cell detection (no registration or classification) via brainmapper on our local HPC cluster with 16 cores and a GPU, with and without the changes proposed in #398, on a CFOS stained whole brain.
* Overall cell candidate detection took ~5 h 30 mins with the changes, compared to ~8 h 30 mins before
* Both runs found ~3.5 millions cells, with 98% matching coordinates
* I compared coordinates on the 38'000 cell candidates found in 20 slices in the middle of the sample brain.
* ~800 cells …
> Optimize cell detection (#398)

- cellfinder/core/tools/system.py
- tests/core/conftest.py
Tests in `brainglobe-workflows` fail on macos-latest as they attempt to run using `mps` which is not available on github runners even though `torch.backends.mps.is_available()` returns `True`.
Moves the logic for forcing PyTorch to use the cpu as the device into the `cellfinder` package. This will hopefully allow the fix from this repo to generalise to `brainglobe-workflows`.
Tested on CI (only place I can reproduce this issue).
No
No
> Moved force cpu into cellfinder function

- pyproject.toml
We shouldn't need to define test dependencies in tox. This PR relies on installing the `dev` and `napari` extras, so hopefully we have one less thing to keep up to date.
Closes https://github.com/brainglobe/cellfinder/issues/284
> Remove test dependency duplication

- cellfinder/core/detect/filters/volume/structure_splitting.py
- tests/core/test_integration/test_detection_structure_splitting.py
Currently volume underflows when we subtract 1, as explained in the bug report. Because volume is unsigned so subtracting from zero will flow back to the max value, that actually means they become bright voxels.
Also, the z calculation shifts the z stack as explained there.
Prevent the underflow by not subtracting from zero entries. Also correctly calculates the z pos of processed middle planes.
Fixes https://github.com/brainglobe/cellfinder/issues/435.
Added a test. Functionality probably has changed though because it was incorrect before.
Without the fix, the newly added test prints the following when test:
```
========================================================================================================== …
```
> Prevent zero underflow in volume

- cellfinder/napari/curation.py
Linting is failing in #445 due to instance checks being flagged as an error now.
Fixes the linting error.
Linting passes with the new ruff version, all tests pass, and visual inspection confirms the function still returns the correct subset of layer types.
No
No
> Conform to new linting rules

- pyproject.toml
Training currently fails because of keras and nump
Temporarily pin to numpy < 2
Workaround for #446
Locally, as described in #446
Nope
Nope
- [ \ ] Tests have been added to cover all new functionality (unit & integration)
- [ \ ] The documentation has been updated to reflect any changes
- [ \ ] The code has been formatted with [pre-commit](https://pre-commit.com/)
> temporarily depend on numpy<2

- pyproject.toml
Currently, training enters an infinite loop at the end of an epoch.
This only happens with `keras==3.6.0`. Temporarily pinning to `3.5.0`.
> Pin `keras` version to 3.5.0

- cellfinder/core/classify/classify.py
See #459 
Check if the `trained_model` ends in `.h5`. If so, warn the user, and load the weights into a default model.
closes #459 
Tested locally with the model weights from the paper.
No.
Yes, will come in a subsequent PR.
> Allow napari GUI to accept custom weights

- pyproject.toml
`keras` 3.7.0 fixed the stalled training bug.
closes #463
> Unpin keras

- cellfinder/core/detect/filters/volume/ball_filter.py
- tests/core/test_unit/test_detect/test_filters/test_volume_filters/test_ball_filter.py
It fixes #479 and makes #482 obsolete.
Before, we used the shorthand of `arr[-count:]` as a proxy for `arr[len(arr)-count:]`. The problem is with a batch size that is exactly equal the kernel size (ball z size), `count` is zero unintentionally. So `self.volume` kept growing without bound as we kept reusing the whole array instead of not appending any of the array, which was the intention.
#479 and #482.
Added pytests. Before the fix the test resulted in failure. Now it fully passes:
```
tests\core\test_unit\test_detect\test_filters\test_volume_filters\test_ball_filter.py FFFF............ …
```
> Use explicit len(arr)-count instead of just -count to handle count=0

- cellfinder/napari/curation.py
- pyproject.toml
Re-useable Qt elements have been moved from brainglobe-utils to [qt-niu](https://github.com/neuroinformatics-unit/qt-niu). This PR changes the imports accordingly.
> Import Qt elements from qt-niu

- pyproject.toml
I put it into the dev dependencies by mistake. Cellfinder should be re-released once this is merged. I've yanked `1.5.0` on PyPI.
> Move qt-niu dependency

- cellfinder/napari/train/train.py
- cellfinder/napari/train/train_containers.py
Enhancement: #425 
Removed the save_weights option from the Napari training plugin to ensure consistency.
Reason:
The detection plugin requires a full model, and having an option to save only weights caused confusion.
What was done:
- Removed all save_weights references from the Napari training plugin.
- Now, only full models are saved after training.
- Impact:
- Simplifies usage and ensures compatibility between training and detection.
> Remove save weights option from training widget

- .gitignore
- pyproject.toml
What is this PR
Bug fix
Why is this PR needed?
This PR updates the PyTorch version to >=2.4.1, skipping 2.4.0 which contained a bug affecting inference on Windows. The bug has been resolved upstream in PyTorch. See [pytorch/pytorch#131958](https://github.com/pytorch/pytorch/issues/131958) for reference.
What does this PR do?
Updates the pyproject.toml dependency list to require torch>=2.4.1
Ensures Cellfinder avoids the buggy PyTorch 2.4.0 version
> Update pinned pytorch version

- cellfinder/core/train/train_yaml.py
This cleans up the TensorFlow-related code in the cellfinder project by:
- Moving Keras imports from within functions to the top of `train_yaml.py`
- Removing the comment about TensorFlow warning suppression from `train_yaml.py`
- These changes align with the project's migration to Keras 3.0 with PyTorch as the default backend, making the codebase cleaner and more maintainable. 
- The functionality remains intact while removing unnecessary TensorFlow-specific error handling and import patterns.
- #423 
- #418 
- Successfully ran all pre-commit hooks locally.
- Verified `train_yaml.py` shows no linting issues after cleaning up imports.
- No
- No
> Fix #423 : Clean up TensorFlow-related code after migrating to Keras 3.0 with PyTorch backend

- cellfinder/napari/curation.py
- tests/napari/test_curation.py
Adds a function to the constructor of curation.py which removes the curation widget's internal layer references (e.g. self.training_data_cell_layer...) if that layer is deleted from the Napari viewer. This prevents the "training data layers already exist, overwrite with empty layers?" popup from occurring in CurationWidget when you delete training data layers from the viewer and then try to create new training data layers from the CurationWidget.
I'm uncertain what other parts of the codebase are affected by …
> Fix for deleted layers hanging around in CurationWidget

- cellfinder/napari/detect/detect_containers.py
- cellfinder/napari/input_container.py
- tests/napari/test_input_containers.py
I noticed while using napari to classify points from a large tiff that had been memmapped, that the tiff would be loaded fully into memory at some point. I traced it down to `asdict` doing a `deepcopy` of all the field values of the data class. Or rather it only does it for non basic object types.
This means that all the data layers inputs get deep copied, even if they are memmaped so that it loads the full data into memory. Which is not wanted.
With this PR, we use our own version of `asdict` that converts the data class into a dict without doing the `deepcopy`.
Please reference any existing issues/PRs that relate to this PR.
I manually tested it in napari and also added a test function.
No.
No.
I think it would be …
> Don't deepcopy input arrays to prevent loading into RAM

- cellfinder/core/detect/detect.py
- cellfinder/core/main.py
- cellfinder/napari/detect/detect.py
- cellfinder/napari/detect/detect_containers.py
- cellfinder/napari/detect/thread_worker.py
- tests/core/test_integration/test_detection.py
To expose GPU/CPU selection and batch size control in the Napari plugin, and to improve usability and performance by automatically handling the `use_scipy` setting depending on the selected device.
I added device selection (CPU/GPU) in the Napari plugin, defaulting to GPU if available (currently only handling "cuda").
I added some docstrings related to `batch_size`. The `batch_size` parameter was already exposed in the Napari plugin for classification.
The `use_scipy` parameter is now handled automatically: if `torch_device` is "cpu", it’s set to `True`; otherwise, `False`. It is no longer exposed in any interface, as requested.
Notes
In `cellfinder/core/main.py`, the parameter passed to the detection step (`detect`) …
> Expose CPU/GPU selection in Napari (default to GPU), remove use_scipy param (always True on CPU), and improve batch_size docstring (#464)

- .github/workflows/test_and_deploy.yml
- pyproject.toml
Adds an extra run of the neuroinformatics/actions/test with napari installed from main. This action will only run during the weekly cron job.
> Run scheduled tests on napari main

- benchmarks/filter_debug.py
- cellfinder/core/detect/filters/volume/structure_splitting.py
This PR depends on https://github.com/brainglobe/cellfinder/pull/542.
Added a file under benchmarks (`filter_debug.py`) that given an input folder containing a list of tiff, it loads it using dask and does full 2d and 3d filtering, cell detection and cluster splitting. For each filtering step it outputs the filtered image so you can see what the step produces and tune parameters. 
Because it's hard to tune all these parameters when you only have the final output (candidate cells), which takes a bit to run and you have to guess at how these input parameters actually affect the outcome. There's already something like this for saving the output of the 3d filtering step, but having the 2d step output in particular is helpful. 
This should also be helpful for …
> Visualize 2d and 3d filtering steps

- cellfinder/core/classify/classify.py
- cellfinder/core/detect/detect.py
- cellfinder/core/detect/filters/setup_filters.py
- cellfinder/core/detect/filters/volume/volume_filter.py
- cellfinder/core/main.py
- cellfinder/napari/detect/detect.py
- cellfinder/napari/detect/detect_containers.py
This depends on https://github.com/brainglobe/cellfinder/pull/542.
`pin_memory` is already used in detection, and will be used in classification. It should be exposed so users can use it to speed up GPU data uploading.
I didn't initially add it to classification as well. But I added it because we will need it and we will need to add it to brainglobe-workflows to pass it on. And making workflows being able to pass this parameter to both detection and classification, even before we start using it, will reduce compatibility issues.
It exposes it in napari and in the main functions. But it defaults to not being enabled due to the requirement of the data memory not being paged out of RAM if it's used. So users will need …
> Expose pin_memory to main and napari
